[build]
  command = "npx ng build --configuration production"
  publish = "dist/portfolio/browser"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
